# Generated by Django 5.2.14 on 2026-09-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Đã ghim'),
        ),
    ]
