# Generated by Django 5.2.14 on 2026-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Bình luận', 'verbose_name_plural': 'Bình luận'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Báo cáo vi phạm', 'verbose_name_plural': 'Báo cáo vi phạm'},
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('song', 'Bài hát'), ('comment', 'Bình luận'), ('user', 'Người dùng'), ('playlist', 'Playlist')], db_index=True, max_length=10),
        ),
    ]
