# Generated by Django 5.2.17 on 2026-08-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('song', 'Bài hát'), ('comment', 'Bình luận'), ('user', 'Người dùng'), ('playlist', 'Playlist')], db_index=True, max_length=10),
        ),
    ]
