apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: playmood
type: Opaque
data:
  SECRET_KEY: Jm93bTYlbnFqal9ucDAoJi1wbnJzdUA5bHhzdTkrKHlwZCN0c15qMXgxMmltZCpneTM=
  CLOUDINARY_CLOUD_NAME: ZHN1b3hub2Nr
  CLOUDINARY_API_KEY: OTc3Njc1NDg1MTQ1MTI2
  CLOUDINARY_API_SECRET: OEVNcm1fVDFWV2RMMXJsMTdSdVJHZkx0N09n
  CLOUDINARY_URL: Y2xvdWRpbmFyeTovLzk3NzY3NTQ4NTE0NTEyNjo4RU1ybV9UMVZXZEwxcmwxN1J1UkdmTHQ3T2dAZHN1b3hub2Nr
  RESEND_API_KEY: cmVfYlY2M3RGdjZfNGh0WXRYN2NVMXlUcGVTaHREZ0hXM213ZA==
  DEFAULT_FROM_EMAIL: bm8tcmVwbHlAdHJhaW5naGllbXRodWh0cS5pZC52bg==
