# Generated by Django 5.2.17 on 2026-08-25 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0006_alter_report_target_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Người tham gia')),
            ],
            options={
                'verbose_name': 'Cuộc trò chuyện',
                'verbose_name_plural': 'Cuộc trò chuyện',
                'db_table': 'chat_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='', verbose_name='Nội dung')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ảnh đính kèm')),
                ('reactions', models.JSONField(blank=True, default=dict, verbose_name='Cảm xúc')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày gửi')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Cuộc trò chuyện')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('shared_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.song', verbose_name='Bài hát chia sẻ')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
