# Generated by Django 5.2.17 on 2026-08-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('music', '0006_alter_report_target_type'),
        ('playlists', '0004_alter_playlist_cover_image_delete_playlistlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album', verbose_name='Album chia sẻ'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlists.playlist', verbose_name='Playlist chia sẻ'),
        ),
    ]
