# Generated by Django 5.2.14 on 2026-08-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_shared_album_message_shared_playlist'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post', verbose_name='Bài viết chia sẻ'),
        ),
    ]
