apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: playmood
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  DATABASE_URL: "postgresql://playmood_user:playmood_pass@postgres-svc:5432/playmood_db"
  REDIS_URL: "redis://redis-svc:6379/0"
  CSRF_TRUSTED_ORIGINS: "http://playmood.local,http://localhost:8000,http://localhost"
  SESSION_COOKIE_SECURE: "False"
  CSRF_COOKIE_SECURE: "False"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  KAFKA_ENABLED: "True"