# Generated by Django 5.2.17 on 2026-09-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, choices=[('song', 'Bài hát'), ('playlist', 'Playlist'), ('comment', 'Bình luận'), ('user', 'Người dùng'), ('follow_req', 'Yêu cầu kết bạn')], max_length=10, null=True),
        ),
    ]
